# Generated by Django 3.1.6 on 2021-07-03 10:39

import account.models
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='nonLoginUser',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('random_code', models.CharField(blank=True, max_length=256, null=True, verbose_name='固有コード')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='名前')),
                ('table', models.PositiveIntegerField(blank=True, null=True, verbose_name='テーブルの番号')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='日付')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='店名')),
                ('logo', models.ImageField(blank=True, max_length=50, null=True, upload_to='logo', verbose_name='ロゴ')),
                ('is_staff', models.BooleanField(default=False, verbose_name='IAM')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', account.models.UserManager()),
            ],
        ),
    ]
