# Generated by Django 3.2.5 on 2021-07-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonloginuser',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='食事中'),
        ),
    ]
