# Generated by Django 3.1.6 on 2021-05-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='ロゴ'),
        ),
    ]
