# Generated by Django 3.2.5 on 2021-07-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonloginuser',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='お会計金額'),
        ),
    ]
