# Generated by Django 3.1.6 on 2021-05-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonloginuser',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='名前'),
        ),
    ]
