# Generated by Django 3.2.5 on 2021-08-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_nonloginuser_allowed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='テーブルの番号')),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='テーブル毎合計')),
                ('active', models.BooleanField(blank=True, default=False, null=True, verbose_name='現在')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='日付')),
            ],
        ),
    ]
