# Generated by Django 3.2.5 on 2021-07-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_nonloginuser_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonloginuser',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='食事中'),
        ),
    ]
