# Generated by Django 3.2.5 on 2021-07-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_nonloginuser_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonloginuser',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='お会計金額'),
        ),
    ]
