# Generated by Django 3.1.6 on 2021-06-05 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_nonloginuser_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nonloginuser',
            options={'verbose_name': 'non_login_user', 'verbose_name_plural': 'non_login_users'},
        ),
    ]
