# Generated by Django 3.2.5 on 2021-07-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_nonloginuser_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonloginuser',
            name='nomiho',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='飲み放題中'),
        ),
    ]
