# Generated by Django 3.1.6 on 2021-06-05 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210605_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nonloginuser',
            options={},
        ),
    ]
