# Generated by Django 3.1.6 on 2021-06-19 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('account', '0004_auto_20210605_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonloginuser',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sessions.session'),
        ),
    ]
