# Generated by Django 3.2.5 on 2021-07-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_nonloginuser_nomiho'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonloginuser',
            name='nomiho_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='飲み放題プラン名'),
        ),
        migrations.AddField(
            model_name='nonloginuser',
            name='nomiho_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='飲み放題の合計金額'),
        ),
    ]
