# Generated by Django 3.2.5 on 2021-07-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210718_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonloginuser',
            name='nomiho_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='飲み放題の合計金額'),
        ),
    ]
