# Generated by Django 3.1.6 on 2021-06-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210620_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonloginuser',
            name='session',
        ),
        migrations.AddField(
            model_name='nonloginuser',
            name='random_code',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='固有コード'),
        ),
    ]
