# Generated by Django 3.1.6 on 2021-05-31 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_nonloginuser_name'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=256, null=True, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='オーダー発生時刻')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.nonloginuser')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.menu')),
            ],
        ),
    ]
