# Generated by Django 3.2.5 on 2021-07-18 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=256, null=True, verbose_name='ステータス')),
                ('num', models.PositiveIntegerField(blank=True, null=True, verbose_name='個数')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='オーダー発生時刻')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.nonloginuser')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(blank=True, null=True, verbose_name='個数')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='カート追加時刻')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.nonloginuser')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.menu')),
            ],
        ),
    ]
