# Generated by Django 3.1.6 on 2021-05-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='テーブルの番号'),
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
