# Generated by Django 3.1.6 on 2021-06-05 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20210605_1115'),
        ('account', '0003_auto_20210605_1250'),
        ('customer', '0002_order_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(blank=True, null=True, verbose_name='個数')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='カート追加時刻')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.nonloginuser')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.menu')),
            ],
        ),
    ]
