# Generated by Django 3.2.5 on 2021-07-31 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('restaurant', '0004_alter_menu_comment'),
        ('customer', '0002_auto_20210719_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.nonloginuser'),
        ),
        migrations.AlterField(
            model_name='order',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.menu'),
        ),
    ]
