# Generated by Django 3.2.5 on 2021-08-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210809_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='request',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='リクエスト'),
        ),
        migrations.AddField(
            model_name='order',
            name='request',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='リクエスト'),
        ),
    ]
