# Generated by Django 3.2.5 on 2021-08-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_option_price'),
        ('customer', '0003_auto_20210814_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='option',
            field=models.ManyToManyField(blank=True, null=True, to='restaurant.Option'),
        ),
        migrations.AddField(
            model_name='order',
            name='option',
            field=models.ManyToManyField(blank=True, null=True, to='restaurant.Option'),
        ),
    ]
