# Generated by Django 3.2.5 on 2021-08-01 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('customer', '0003_auto_20210731_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomihoOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=256, null=True, verbose_name='ステータス')),
                ('nomiho', models.CharField(blank=True, max_length=256, null=True, verbose_name='飲み放題プラン名')),
                ('table', models.PositiveIntegerField(blank=True, null=True, verbose_name='テーブル番号')),
                ('num', models.PositiveIntegerField(blank=True, null=True, verbose_name='人数')),
                ('curr', models.BooleanField(blank=True, default=False, null=True, verbose_name='今回分か否か')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='飲み放題開始時刻')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.nonloginuser')),
            ],
        ),
    ]
