from beanstalk.settings import (
    FIREBASE_APIKEY,
    FIREBASE_AUTHDOMAIN,
    FIREBASE_PROJECTID,
    FIREBASE_STORAGEBUCKET,
    FIREBASE_MESSAGINGSENDERID,
    FIREBASE_APPID,
    FIREBASE_MEASUREMENTID,
    ONE_SIGNAL_APP_ID
)


def firebase(request):

    ctx = {
        'FIREBASE_APIKEY': FIREBASE_APIKEY,
        'FIREBASE_AUTHDOMAIN': FIREBASE_AUTHDOMAIN,
        'FIREBASE_PROJECTID': FIREBASE_PROJECTID,
        'FIREBASE_STORAGEBUCKET': FIREBASE_STORAGEBUCKET,
        'FIREBASE_MESSAGINGSENDERID': FIREBASE_MESSAGINGSENDERID,
        'FIREBASE_APPID': FIREBASE_APPID,
        'FIREBASE_MEASUREMENTID': FIREBASE_MEASUREMENTID,
    }

    return ctx


def onesignal(request):

    ctx = {
        'ONE_SIGNAL_APP_ID': ONE_SIGNAL_APP_ID,
    }

    return ctx
