# Generated by Django 3.1.6 on 2021-05-30 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='表示名')),
                ('type', models.CharField(blank=True, max_length=256, null=True, verbose_name='カテゴリ')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='価格')),
                ('img', models.ImageField(blank=True, max_length=50, null=True, upload_to='img', verbose_name='イメージ画像')),
                ('allergies', models.CharField(blank=True, max_length=256, null=True, verbose_name='アレルギー')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='作成日')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='カテゴリ')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='作成日')),
                ('which', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.menu')),
            ],
        ),
    ]
