# Generated by Django 3.2.5 on 2021-07-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomiho',
            name='comment',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='一押しポイント'),
        ),
        migrations.AddField(
            model_name='nomiho',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='制限時間（分）'),
        ),
    ]
