# Generated by Django 3.2.5 on 2021-08-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='オプション')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='作成日')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='option',
            field=models.ManyToManyField(blank=True, null=True, to='restaurant.Option'),
        ),
    ]
