# Generated by Django 3.1.6 on 2021-05-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='img',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='img', verbose_name='イメージ画像'),
        ),
    ]
