# Generated by Django 3.2.5 on 2021-07-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='nomiho',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='飲み放題用カテゴリ'),
        ),
    ]
