# Generated by Django 3.1.6 on 2021-05-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='ingredient',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='アレルギー食品'),
        ),
    ]
