# Generated by Django 3.2.5 on 2021-07-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_chef_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='コメント'),
        ),
    ]
