# Generated by Django 3.1.6 on 2021-05-31 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20210601_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='which',
            new_name='category',
        ),
    ]
