# Generated by Django 3.2.5 on 2021-07-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_menu_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='コメント'),
        ),
    ]
