# Generated by Django 3.2.5 on 2021-08-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_option_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='価格'),
        ),
    ]
