# Generated by Django 3.1.6 on 2021-06-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20210601_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='イメージ画像'),
        ),
    ]
