# Generated by Django 3.1.6 on 2021-06-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20210610_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='allergies',
        ),
        migrations.AddField(
            model_name='menu',
            name='allergies',
            field=models.ManyToManyField(blank=True, null=True, to='restaurant.Allergy'),
        ),
    ]
